/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Window;
import javax.swing.JButton;

/**
 *
 * @author Rahmadika Kemala Salsabiela 
 */
public class HomeFrame extends javax.swing.JFrame {
    private PublikasiModel publikasiModel;
    private PublikasiView publikasiView;
    private PublikasiController publikasiController;
    
    public HomeFrame() {
        initComponents();
       
        publikasiModel = new PublikasiModel();
        publikasiView = new PublikasiView();
        publikasiController = new PublikasiController(publikasiModel, publikasiView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openPublikasiViewButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openPublikasiViewButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        openPublikasiViewButton.setText("Open Pendataan Publikasi ");
        openPublikasiViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPublikasiViewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(openPublikasiViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 210, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© Rahmadika Kemala Salsabiela (222212828) ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openPublikasiViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPublikasiViewButtonActionPerformed
        // Set PublikasiController untuk PublikasiView
        publikasiView.setController(publikasiController);
        // Display PublikasiView
        publikasiView.setVisible(true);
    }//GEN-LAST:event_openPublikasiViewButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // Mendapatkan semua jendela yang terbuka
        Window[] windows = Window.getWindows();

        // Menutup setiap jendela
        for (Window window : windows) {
            window.dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton openPublikasiViewButton;
    // End of variables declaration//GEN-END:variables
}
